version: 2
jobs:
  Test:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout
      - run:
          name: Install jest gloablly
          command: npm install -g jest
      - run:
          name: Run tests
          command: npm run test
  Deploy:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout
      - run:
          name: Deploy to heroku
          environment:
            HEROKU_API_KEY: 194d0430-242a-49d0-bc7d-8f0da38841ae
            HEROKU_APP_NAME: glamourng
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  my_workflow:
    jobs:
      - Test
      - Deploy:
          requires:
            -Test
          # filters:
          #   branches:
          #     only: master